config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'profiles#index'
  resources 'profiles'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :company, presence: true
  validates :name, presence: true
  validates :employee_num, presence: true
  validates :start_time, presence: true
  validates :ending_time, presence: true
  validates :regular_holiday, presence: true
  validates :tel, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = Profile.all 
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.create(profile_params)
    @profile.save
  end

  def show
    
  end

  private
  
  def profile_params
    params.require(:profile).permit(:company, :name, :employee_num, :start_time, :ending_time, :regular_holiday, :tel, :postal_code, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SenteiApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="<%= controller.controller_name %>-<%= controller.action_name %>">
    <header>
      <%= render 'shared/header' %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
<div class="content-wrapper">
  <div class="head-section">
    <input  placeholder="キーワードを入力">
  </div>
  <div class="content">
    <div class="image">
      <%= image_tag "mako.jpeg" %>
    </div>
    <div class="information">
      <div class="company">
        神野造園土木
      </div>
      <div class="explanation">
        病院・飲食店・美容院・ネイルサロン・Bar・学生塾など、いろいろな業種の
        病院・飲食店・美容院・ネイルサロン・Bar・学生塾など、いろいろな業種の
      </div>
      <div class="tel-button">
        <div class="tel">
          TEL 0120-1234-5678
        </div>
        <div class="button">
          <%= link_to "詳細を確認する", "profiles/show" %>
        </div>
      </div>
    </div>  
  </div>
</div>

app/views/profiles/new.html.erb
<div class="content-wrapper">
  <div class="head-section">
    <h2>プロフィール設定</h2>
  </div>

  <%= form_with model: @profile, url: root_path, method: :post, local: true do |form| %>
    <div class="field">
      <%= form.label "会社名" %>
      <%= form.text_field :company %>
    </div>

    <div class="field">
      <%= form.label "名前" %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label "従業員数" %>
      <%= form.number_field :employee_num, placeholder: "半角数字" %>
    </div>

    <div class="field">
      <%= form.label "営業時間" %>
      <div class="time">
        <%= form.time_field :start_time %>&nbsp;〜&nbsp;<%= form.time_field :ending_time %>
      </div>
    </div>

    <div class="field">
      <%= form.label "定休日" %>
      <%= form.text_field :regular_holiday %>
    </div>

    <div class="field">
      <%= form.label "電話番号(ハイフンなし)" %>
      <%= form.text_field :tel, placeholder: "半角数字" %>
    </div>

    <div class="field">
      <%= form.label "郵便番号" %>
      <%= form.text_field :postal_code %>
    </div>

    <div class="field">
      <%= form.label "住所" %>
      <%= form.text_field :address %>
    </div>
    
    <div class="actions">
      <%= form.submit "作成" %>
    </div>
  <% end %>
</div>

app/views/profiles/show.html.erb
<div class="content-wrapper">
  <div class="content">
    <div class="image">
      <%= image_tag "mako.jpeg" %> 
    </div>
    <div class="information">
      <div class="company">
        神野造園土木
      </div>
      <div class="information-list">
        <div class="information-block">
          <p>代表</p>
          <p>神野洋次</p>
        </div>
        <div class="information-block">
          <p>従業員</p>
          <p>1人</p>
        </div>
        <div class="information-block">
          <p>営業時間</p>
          <p>7:00 ~ 18:00</p>
        </div>
        <div class="information-block">
          <p>定休日</p>
          <p>年中無休</p>
        </div>
        <div class="information-block">
          <p>電話番号</p>
          <p>0120-1234-5678</p>
        </div>
        <div class="information-block">
          <p>所在地</p>
          <p>〒 000-0000</br>大阪府渋谷区一丁目2-3</p>
        </div>
      </div>
    </div>
  </div>
  <div class="button">
    <%= link_to "プロフィールを変更", new_profile_path %>
    <%= link_to "メッセージ", new_profile_path %>
    <%= link_to "フォロー", new_profile_path %>
    <%= link_to "フォロー中", new_profile_path %>
  </div>
  <div class="explanation">
    <p>
      病院・飲食店・美容院・ネイルサロン・Bar・学生塾など、いろいろな業種の
      病院・飲食店・美容院・ネイルサロン・Bar・学生塾など、いろいろな業種の
      病院・飲食店・美容院・ネイルサロン・Bar・学生塾など、いろいろな業種の
      病院・飲食店・美容院・ネイルサロン・Bar・学生塾など、いろいろな業種の
      病院・飲食店・美容院・ネイルサロン・Bar・学生塾など、いろいろな業種の
      病院・飲食店・美容院・ネイルサロン・Bar・学生塾など、いろ
    </p>
  </div>
  <div class="item-list">
    <ul>
      <li><%= link_to "実績" %></li>
      <li><%= link_to "予定表" %></li>
      <li><%= link_to "求人" %></li>
    </ul>
  </div>
</div>

app/views/shared/_header.html.erb
<nav>
  <div class="logo">
    <h1><%= link_to "Sentei", root_path %></h1>
  </div>
  <div class="header-list">
    <ul>
      <li><%= link_to "ホーム", root_path %></li>
      <li><%= link_to "求人" %></li>
      <% if user_signed_in? %>
        <li><%= link_to "実績" %></li>
        <li><%= link_to "メッセージ" %></li>
        <li><%= link_to "プロフィール" %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか?" } %></li>
      <% else %>
        <li><%= link_to "ログイン", new_user_session_path %></li>
      <% end %>
      
    </ul>
  </div>
</nav>